services:
  glint-web: 
    build:
      context: ./apps/web-client/
      target: development
    image: glint-web:dev
    container_name: glint-web-dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web-client:/glint/src
      - /glint/src/node_modules
    depends_on:
      glint-api:
        condition: service_started
    networks:
      - glint-network
    
  glint-api:
    build:
      context: ./apps/backend/src/Glint.HttpApi/
      target: development
    image: glint-api:dev
    container_name: glint-api-dev
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__Redis=redis:6379,password=${REDIS_PASSWORD}
    volumes:
      - ./apps/backend/src:/glint/src
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - glint-network
  
  glint-media-worker:
    build:
      context: ./apps/backend/src/Glint.MediaWorker/
      target: development
    image: glint-media-worker:dev
    container_name: glint-media-worker-dev
    environment:
      - ConnectionStrings__Redis=redis:6379,password=${REDIS_PASSWORD}
    volumes:
      - ./apps/backend/src:/glint/src
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - glint-network

  redis:
    image: redis:8.4.0-alpine
    container_name: glint-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - glint_redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - glint-network
    
  redisinsight:
    image: redis/redisinsight:3.0.3
    container_name: glint-redisinsight-dev
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - glint-network
    
  postgres:
    image: postgres:18.2-alpine
    container_name: glint-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - glint_postgres_data:/var/lib/postgresql
    networks:
      - glint-network

networks:
  glint-network:
    driver: bridge

volumes:
  glint_redis_data:
  glint_postgres_data:
