<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Glint.Domain\Glint.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    </ItemGroup>

</Project>
